export const contractOptionsBase = [
  { value: 'CDI', labelKey: 'permanentContract' },
  { value: 'CDD', labelKey: 'fixedTermContract' },
  { value: 'alternance', labelKey: 'apprenticeship' },
  { value: 'interim', labelKey: 'temporary' },
  { value: 'stage', labelKey: 'internship' },
  { value: 'saison', labelKey: 'seasonal' },
] as const;

export const domainOptionsBase = [
  { value: 'service_aux_personnes', labelKey: 'personalServices' },
  { value: 'automobile', labelKey: 'automotive' },
  { value: 'esthetique_coiffure', labelKey: 'beautyHairdressing' },
  { value: 'onglerie', labelKey: 'nailCare' },
  { value: 'nettoyage', labelKey: 'cleaning' },
  { value: 'restauration', labelKey: 'catering' },
  { value: 'hotellerie', labelKey: 'hospitality' },
  { value: 'commerce', labelKey: 'retail' },
  { value: 'animation', labelKey: 'animation' },
  { value: 'agricole', labelKey: 'agricultural' },
  { value: 'boucherie', labelKey: 'butchery' },
  { value: 'administratif', labelKey: 'administrative' },
  { value: 'secretariat', labelKey: 'secretarial' },
  { value: 'transport', labelKey: 'transport' },
  { value: 'logistique', labelKey: 'logistics' },
  { value: 'Agro alimentaire', labelKey: 'foodProcessing' },
  { value: 'immobilier', labelKey: 'realEstate' },
  { value: 'maconnerie', labelKey: 'masonry' },
  { value: 'electricite', labelKey: 'electricity' },
  { value: 'telecom', labelKey: 'telecommunications' },
  { value: 'petite_enfance', labelKey: 'earlyChildhood' },
  { value: 'boulangerie', labelKey: 'bakery' },
  { value: 'medical', labelKey: 'medical' },
  { value: 'pret_a_porter', labelKey: 'readyToWear' },
  { value: 'grande_distribution', labelKey: 'massRetail' },
  { value: 'ambulance', labelKey: 'ambulance' },
  { value: 'maison_de_retraite', labelKey: 'retirementHome' },
  { value: 'baby_sitting', labelKey: 'babySitting' },
  { value: 'comptabilite', labelKey: 'accounting' },
  { value: 'marketing', labelKey: 'marketing' },
  { value: 'btp', labelKey: 'construction' },
  { value: 'patisserie', labelKey: 'pastry' },
  { value: 'pharmaceutique', labelKey: 'pharmaceutical' },
  { value: 'poissonnerie', labelKey: 'fishmonger' },
  { value: 'industriel', labelKey: 'industrial' },
  { value: 'livraison', labelKey: 'delivery' },
] as const;

export const scheduleOptionsBase = [
  { value: 'matin', labelKey: 'morning' },
  { value: 'apres_midi', labelKey: 'afternoon' },
  { value: 'soiree', labelKey: 'evening' },
  { value: 'nuit', labelKey: 'night' },
  { value: 'horaire_bureau', labelKey: 'officeHours' },
] as const;

export const workingTimeOptionsBase = [
  { value: 'temps_plein', labelKey: 'fullTime' },
  { value: 'temps_partiel', labelKey: 'partTime' },
] as const;

export const beginningOptionsBase = [
  { value: 'des_maintenant', labelKey: 'rightNow' },
  { value: '1_2_semaines', labelKey: 'oneToTwoWeeks' },
  { value: '1_mois', labelKey: 'oneMonth' },
  { value: 'plus_tard', labelKey: 'later' },
] as const;

export const competenceOptionsBase = [
  { value: 'accueil_client', labelKey: 'customerReception' },
  { value: 'accueil_patient', labelKey: 'patientReception' },
  { value: 'reception_marchandise', labelKey: 'goodsReception' },
  { value: 'service_en_salle', labelKey: 'tableService' },
  { value: 'cuisine', labelKey: 'cooking' },
  { value: 'cantine', labelKey: 'canteen' },
  { value: 'decoration', labelKey: 'decoration' },
  { value: 'maquillage', labelKey: 'makeup' },
  { value: 'mode', labelKey: 'fashion' },
  { value: 'poids_lourd', labelKey: 'heavyGoods' },
  { value: 'manutention', labelKey: 'handling' },
  { value: 'mise_en_rayon', labelKey: 'shelfStocking' },
  { value: 'barman', labelKey: 'bartender' },
  { value: 'chef_d_equipe', labelKey: 'teamLeader' },
  { value: 'informatique', labelKey: 'computerSkills' },
  { value: 'hygiene', labelKey: 'hygiene' },
  { value: 'caces', labelKey: 'forkliftCertification' },
  { value: 'bricolage', labelKey: 'diy' },
  { value: 'jardinage', labelKey: 'gardening' },
  { value: 'pack_office', labelKey: 'msOffice' },
  { value: 'gestion_des_stocks', labelKey: 'inventoryManagement' },
  { value: 'magasinier', labelKey: 'warehouseWorker' },
  { value: 'preparateur_de_commande', labelKey: 'orderPicker' },
  { value: 'maintenance', labelKey: 'maintenance' },
  { value: 'mobilite', labelKey: 'mobility' },
  { value: 'maitre_nageur', labelKey: 'lifeguard' },
  { value: 'moto', labelKey: 'motorcycle' },
  { value: 'entretien', labelKey: 'upkeep' },
  { value: 'camping', labelKey: 'camping' },
  { value: 'renovation', labelKey: 'renovation' },
  { value: 'distribution', labelKey: 'distribution' },
  { value: 'gestion_des_reseaux_sociaux', labelKey: 'socialMediaManagement' },
  { value: 'dactylographie', labelKey: 'typing' },
  { value: 'tenue_de_caisse', labelKey: 'cashRegister' },
] as const;

export const daysOptionsBase = [
  { value: 'L', labelKey: 'monday' },
  { value: 'M1', labelKey: 'tuesday' },
  { value: 'M2', labelKey: 'wednesday' },
  { value: 'J', labelKey: 'thursday' },
  { value: 'V', labelKey: 'friday' },
  { value: 'S', labelKey: 'saturday' },
  { value: 'D', labelKey: 'sunday' },
] as const;

export const filterTypes = {
  contracts: contractOptionsBase,
  domain: domainOptionsBase,
  schedules: scheduleOptionsBase,
  workingTime: workingTimeOptionsBase,
  availability: beginningOptionsBase,
  days: daysOptionsBase,
  skills: competenceOptionsBase,
} as const;
