export const currencies = [
  { label: 'Euro', value: 'EUR', symbol: '€' },
  { label: 'US Dollar', value: 'USD', symbol: '$' },
  { label: 'Russian Ruble', value: 'RUB', symbol: '₽' },
  { label: 'Sri Lankan Rupee', value: 'LKR', symbol: 'Rs' },
  { label: 'Japanese Yen', value: 'JPY', symbol: '¥' },
]

// export const currencies = [
//   {label: 'French Euro', value: 'EUR', symbol: '€'},
//   {label: 'US Dollar', value: 'USD', symbol: '$'},
// //   {label: 'Singapore Dollar', value: 'SGD', symbol: '$'},
//   {label: 'United Arab Emirates Dirham', value: 'AED', symbol: 'د.إ'},
//   {label: 'Afghan Afghani', value: 'AFN', symbol: '؋'},
//   {label: 'Albanian Lek', value: 'ALL', symbol: 'L'},
//   {label: 'Armenian Dram', value: 'AMD', symbol: '֏'},
//   {label: 'Netherlands Antillean Guilder', value: 'ANG', symbol: 'ƒ'},
//   {label: 'Angolan Kwanza', value: 'AOA', symbol: 'Kz'},
//   {label: 'Argentine Peso', value: 'ARS', symbol: '$'},
//   {label: 'Australian Dollar', value: 'AUD', symbol: '$'},
//   {label: 'Aruban Florin', value: 'AWG', symbol: 'ƒ'},
//   {label: 'Azerbaijani Manat', value: 'AZN', symbol: '₼'},
//   {
//     label: 'Bosnia and Herzegovina Convertible Mark',
//     value: 'BAM',
//     symbol: 'KM',
//   },
//   {label: 'Barbadian Dollar', value: 'BBD', symbol: 'Bds$'},
//   {label: 'Bangladeshi Taka', value: 'BDT', symbol: '৳'},
//   {label: 'Bulgarian Lev', value: 'BGN', symbol: 'лв'},
// //   {label: 'Bahraini Dinar', value: 'BHD', symbol: '.د.ب'},
//   {label: 'Burundian Franc', value: 'BIF', symbol: 'FBu'},
//   {label: 'Bermudian Dollar', value: 'BMD', symbol: '$'},
//   {label: 'Brunei Dollar', value: 'BND', symbol: 'B$'},
//   {label: 'Bolivian Boliviano', value: 'BOB', symbol: 'Bs.'},
//   {label: 'Brazilian Real', value: 'BRL', symbol: 'R$'},
//   {label: 'Abkhazian Ruble', value: 'RUB', symbol: '₽'},
// //   {label: 'Afghan Afghani', value: 'AFN', symbol: '؋'},
//   {label: 'Euro', value: 'EUR', symbol: '€'},
// //   {label: 'Albanian Lek', value: 'ALL', symbol: 'L'},
//   {label: 'Andorran Euro', value: 'EUR', symbol: '€'},
// //   {label: 'Armenian Dram', value: 'AMD', symbol: '֏'},
//   {label: 'Artsakh Dram', value: 'AMD', symbol: '֏'},
//   {label: 'Austrian Euro', value: 'EUR', symbol: '€'},
// //   {label: 'Azerbaijani Manat', value: 'AZN', symbol: '₼'},
//   {label: 'Bahraini Dinar', value: 'BHD', symbol: '.د.ب'},
// //   {label: 'Bangladeshi Taka', value: 'BDT', symbol: '৳'},
//   {label: 'Belarusian Ruble', value: 'BYN', symbol: 'Br'},
//   {label: 'Belgian Euro', value: 'EUR', symbol: '€'},
//   {label: 'Bhutanese Ngultrum', value: 'BTN', symbol: 'Nu.'},
// //   {
// //     label: 'Bosnia and Herzegovina Convertible Mark',
// //     value: 'BAM',
// //     symbol: 'KM',
// //   },
// //   {label: 'British Pound Sterling', value: 'GBP', symbol: '£'},
// //   {label: 'Brunei Dollar', value: 'BND', symbol: 'B$'},
// //   {label: 'Bulgarian Lev', value: 'BGN', symbol: 'лв'},
//   {label: 'Cambodian Riel', value: 'KHR', symbol: '៛'},
//   {label: 'Chinese Yuan', value: 'CNY', symbol: '¥'},
//   {label: 'Christmas Island (Australia) Dollar', value: 'AUD', symbol: '$'},
//   {
//     label: 'Cocos (Keeling) Islands (Australia) Dollar',
//     value: 'AUD',
//     symbol: '$',
//   },
//   {label: 'Croatian Kuna', value: 'EUR', symbol: '€'},
//   {label: 'Cypriot Euro', value: 'EUR', symbol: '€'},
//   {label: 'Czech Republic Koruna', value: 'CZK', symbol: 'Kč'},
//   {label: 'Danish Krone', value: 'DKK', symbol: 'kr'},
//   {label: 'Estonian Euro', value: 'EUR', symbol: '€'},
//   {label: 'Finnish Euro', value: 'EUR', symbol: '€'},
//   {label: 'Georgian Lari', value: 'GEL', symbol: '₾'},
//   {label: 'German Euro', value: 'EUR', symbol: '€'},
//   {label: 'Greek Euro', value: 'EUR', symbol: '€'},
//   {label: 'Hong Kong Dollar', value: 'HKD', symbol: 'HK$'},
//   {label: 'Hungarian Forint', value: 'HUF', symbol: 'Ft'},
//   {label: 'Icelandic Króna', value: 'ISK', symbol: 'kr'},
//   {label: 'Indian Rupee', value: 'INR', symbol: '₹'},
//   {label: 'Indonesian Rupiah', value: 'IDR', symbol: 'Rp'},
//   {label: 'Iranian Rial', value: 'IRR', symbol: '﷼'},
//   {label: 'Iraqi Dinar', value: 'IQD', symbol: 'ع.د'},
//   {label: 'Irish Euro', value: 'EUR', symbol: '€'},
//   {label: 'Israeli New Shekel', value: 'ILS', symbol: '₪'},
//   {label: 'Italian Euro', value: 'EUR', symbol: '€'},
//   {label: 'Japanese Yen', value: 'JPY', symbol: '¥'},
//   {label: 'Jordanian Dinar', value: 'JOD', symbol: 'JD'},
//   {label: 'Kazakhstani Tenge', value: 'KZT', symbol: '₸'},
//   {label: 'Kuwaiti Dinar', value: 'KWD', symbol: 'KD'},
//   {label: 'Kyrgyzstani Som', value: 'KGS', symbol: 'som'},
//   {label: 'Laotian Kip', value: 'LAK', symbol: '₭'},
//   {label: 'Latvian Euro', value: 'EUR', symbol: '€'},
//   {label: 'Lebanese Pound', value: 'LBP', symbol: 'ل.ل'},
//   {label: 'Liechtenstein Swiss Franc', value: 'CHF', symbol: 'CHF'},
//   {label: 'Lithuanian Euro', value: 'EUR', symbol: '€'},
//   {label: 'Luxembourg Euro', value: 'EUR', symbol: '€'},
//   {label: 'Macanese Pataca', value: 'MOP', symbol: 'MOP$'},
//   {label: 'Malaysian Ringgit', value: 'MYR', symbol: 'RM'},
//   {label: 'Maldivian Rufiyaa', value: 'MVR', symbol: 'ރ.'},
//   {label: 'Maltese Euro', value: 'EUR', symbol: '€'},
//   {label: 'Moldovan Leu', value: 'MDL', symbol: 'L'},
//   {label: 'Monaco Euro', value: 'EUR', symbol: '€'},
//   {label: 'Mongolian Tugrik', value: 'MNT', symbol: '₮'},
//   {label: 'Montenegrin Euro', value: 'EUR', symbol: '€'},
//   {label: 'Myanmar Kyat', value: 'MMK', symbol: 'Ks'},
//   {label: 'Nepalese Rupee', value: 'NPR', symbol: 'रू'},
//   {label: 'Dutch Euro', value: 'EUR', symbol: '€'},
//   {label: 'North Korean Won', value: 'KPW', symbol: '₩'},
//   {label: 'North Macedonian Denar', value: 'MKD', symbol: 'ден'},
//   {label: 'Northern Cypriot Lira', value: 'TRY', symbol: '₺'},
//   {label: 'Norwegian Krone', value: 'NOK', symbol: 'kr'},
//   {label: 'Omani Rial', value: 'OMR', symbol: 'ر.ع.'},
//   {label: 'Pakistani Rupee', value: 'PKR', symbol: 'Rs'},
//   {label: 'Palestinian New Shekel', value: 'ILS', symbol: '₪'},
//   {label: 'Philippine Peso', value: 'PHP', symbol: '₱'},
//   {label: 'Polish Złoty', value: 'PLN', symbol: 'zł'},
//   {label: 'Portuguese Euro', value: 'EUR', symbol: '€'},
//   {label: 'Qatari Riyal', value: 'QAR', symbol: 'ر.ق'},
//   {label: 'Romanian Leu', value: 'RON', symbol: 'lei'},
//   {label: 'Russian Ruble', value: 'RUB', symbol: '₽'},
//   {label: 'San Marino Euro', value: 'EUR', symbol: '€'},
//   {label: 'Saudi Riyal', value: 'SAR', symbol: 'ر.س'},
//   {label: 'Serbian Dinar', value: 'RSD', symbol: 'din.'},
//   {label: 'Singapore Dollar', value: 'SGD', symbol: '$'},
//   {label: 'Slovak Euro', value: 'EUR', symbol: '€'},
//   {label: 'Slovenian Euro', value: 'EUR', symbol: '€'},
//   {label: 'South Korean Won', value: 'KRW', symbol: '₩'},
//   {label: 'South Ossetian Ruble', value: 'RUB', symbol: '₽'},
//   {label: 'Spanish Euro', value: 'EUR', symbol: '€'},
//   {label: 'Sri Lankan Rupee', value: 'LKR', symbol: 'Rs'},
//   {label: 'Swedish Krona', value: 'SEK', symbol: 'kr'},
//   {label: 'Swiss Franc', value: 'CHF', symbol: 'CHF'},
//   {label: 'Syrian Pound', value: 'SYP', symbol: '£S'},
//   {label: 'Taiwanese Dollar', value: 'TWD', symbol: 'NT$'},
//   {label: 'Tajikistani Somoni', value: 'TJS', symbol: 'смн'},
//   {label: 'Thai Baht', value: 'THB', symbol: '฿'},
//   {label: 'Timor-Leste US Dollar', value: 'USD', symbol: '$'},
//   {label: 'Turkish Lira', value: 'TRY', symbol: '₺'},
//   {label: 'Turkmenistani Manat', value: 'TMT', symbol: 'T'},
//   {label: 'Ukrainian Hryvnia', value: 'UAH', symbol: '₴'},
//   {label: 'Emirati Dirham', value: 'AED', symbol: 'د.إ'},
//   {label: 'British Pound Sterling', value: 'GBP', symbol: '£'},
//   {label: 'Uzbekistani Som', value: 'UZS', symbol: 'soʻm'},
//   {label: 'Vatican Euro', value: 'EUR', symbol: '€'},
//   {label: 'Vietnamese Đồng', value: 'VND', symbol: '₫'},
//   {label: 'Yemeni Rial', value: 'YER', symbol: '﷼'},
// ];