export const SIGN_UP_FORM = 'SIGN_UP_FORM';
export const SIGN_IN_FORM = 'SIGN_IN_FORM';
export const ACCOUNT_CREATION_FORM = 'ACCOUNT_CREATION_FORM';
export const CONFIRMATION_DETAILS_FORM = 'CONFIRMATION_DETAILS_FORM';
export const JOB_CARD_CREATION_FORM = 'JOB_CARD_CREATION_FORM';
