export const BASE_URL = import.meta.env.VITE_BASE_URL
export const BASE_URL_COGNITO = import.meta.env.BASE_URL_COGNITO

export const getAllJobsUrl = BASE_URL + '/jobs'
export const createJobUrl = BASE_URL + '/jobs/create'
export const updateJobUrl = BASE_URL + '/jobs/update'
export const filterJobsUrl = BASE_URL + '/jobs/filter'
export const enableJobUrl = BASE_URL + '/jobs/enable'
export const disableJobUrl = BASE_URL + '/jobs/disable'
export const deleteJobUrl = BASE_URL + '/jobs/delete'

export const getAllEnterprisesUrl = BASE_URL + '/enterprises'
export const getEnterpriseByIdUrl = BASE_URL + '/enterprises'
export const searchEnterprisesUrl = BASE_URL + '/enterprises/search'
export const createEnterpriseUrl = BASE_URL + '/enterprises/create'
export const updateEnterpriseUrl = BASE_URL + '/enterprises/update'
export const enableEnterpriseUrl = BASE_URL + '/enterprises/enable'
export const disableEnterpriseUrl = BASE_URL + '/enterprises/disable'
export const deleteEnterpriseUrl = BASE_URL + '/enterprises/delete'
export const filterEnterprisesUrl = BASE_URL + '/enterprises/filter'
export const resetEnterprisesPasswordEmailSendUrl = BASE_URL + '/enterprises/send-reset-password'

export const candidateGetAllUrl = BASE_URL + '/candidates'
export const candidateGetByIdUrl = BASE_URL + '/candidates'
export const candidateCreateUrl = BASE_URL + '/candidates/create'
export const candidateUpdateUrl = BASE_URL + '/candidates/update'
export const candidateDeleteUrl = BASE_URL + '/candidates/delete'
export const candidateSuspendUrl = BASE_URL + '/candidates/suspend'
export const activeCandidateUrl = BASE_URL + '/candidates/active'
export const displayCandidateUrl = BASE_URL + '/candidates/unhide'
export const hideCandidateUrl = BASE_URL + '/candidates/hide'
export const filterCandidatesUrl = BASE_URL + '/candidates/filter'
export const resetCandidatePasswordUrl = BASE_URL + '/candidates/resetpassword/'
export const resetPasswordEmailSendUrl = BASE_URL + '/candidates/send-reset-password'

export const getAllAdminsUrl = BASE_URL + '/adminUsers'
export const getAdminByIdUrl = BASE_URL + '/adminUsers'
export const createAdminUrl = BASE_URL + '/adminUsers/create'
export const updateAdminUrl = BASE_URL + '/adminUsers/update'
export const enableAdminUrl = BASE_URL + '/adminUsers/enable'
export const disableAdminUrl = BASE_URL + '/adminUsers/disable'
export const deleteAdminUrl = BASE_URL + '/adminUsers/delete'
export const resetAdminPasswordEmailSendUrl = BASE_URL + '/adminUsers/send-reset-password'
export const resetAdminPasswordUrl = BASE_URL + '/adminUsers/resetpassword/'

export const getSignedUrl = BASE_URL + '/presigned-url'
export const deleteImageUrl = BASE_URL + '/image/delete'

export const adminLoginUrl = BASE_URL + '/auth/login'
export const getDashboardMetricsUrl = BASE_URL + '/dashboard/metrics'
export const getDashboardRecentJobsUrl = BASE_URL + '/recent-jobs'
export const getDashboardRecentEnterprisesUrl = BASE_URL + '/recent-enterprises'
